### ISSUE TITLE
Installer not work in aarch64 ISO desktop

### ISSUE THREAD

**Issue by simper** [BredOS/Bakery#13]
I got below error and the GUI cannot start the installer under a proxmox VM environment, with 24.12.22 mainline iso:

> ┌─[bred@bredos]─(~/Desktop)
> └─[05:20]-(^_^)-[$] sudo -E Bakery --gui
> Starting logger..
> Logging to: /home/bred/.bredos/bakery/logs/BAKERY-2024-12-28-05-21-07.log
>     INFO: Logger initialized.
>     INFO: Dry run = False
> 
> (bakery-gui.py:1774): Gtk-WARNING **: 05:21:07.773: Unable to acquire session bus: Error receiving data: Connection reset by peer
> 
> (bakery-gui.py:1774): GLib-GIO-CRITICAL **: 05:21:07.782: g_menu_item_set_attribute_value: assertion 'valid_attribute_name (attribute)' failed
> 
> (bakery-gui.py:1774): Gtk-CRITICAL **: 05:21:07.793: gtk_widget_add_css_class: assertion 'css_class[0] != '.'' failed
> /usr/share/bakery/bakery-gui.py:166: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
>   context = widget.get_style_context()
> /usr/share/bakery/bakery-gui.py:167: DeprecationWarning: Gtk.StyleContext.add_provider is deprecated
>   context.add_provider(css_provider, Gtk.STYLE_PROVIDER_PRIORITY_USER)
> /usr/share/bakery/bakery-gui.py:694: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
>   date = dates.format_date(date=datetime.utcnow(), format="full", locale=locale_)
> /usr/share/bakery/bakery-gui.py:695: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
>   time = dates.format_time(time=datetime.utcnow(), format="long", locale=locale_)
>  WARNING: abnt2 not in _kbmodelmap
>  WARNING: jp106 not in _kbmodelmap
>  WARNING: kr106 not in _kbmodelmap
>  WARNING: abnt2 not in _kbmodelmap
>  WARNING: jp106 not in _kbmodelmap
>  WARNING: kr106 not in _kbmodelmap
>     INFO: Internet status: True
> /usr/share/bakery/bakery-gui.py:820: DeprecationWarning: Gtk.StyleContext.remove_class is deprecated
>   spin_entry.get_style_context().remove_class("error")
> /usr/lib/python3.12/site-packages/gi/_gtktemplate.py:186: Warning: value "-1" of type 'gint' is invalid or out of range for property 'margin-start' of type 'gint'
>   base_init_template(self)
> 
> (bakery-gui.py:1774): Gtk-CRITICAL **: 05:21:19.779: gtk_widget_add_css_class: assertion 'css_class[0] != '.'' failed
> 
> (bakery-gui.py:1774): Gtk-CRITICAL **: 05:21:19.779: gtk_widget_add_css_class: assertion 'css_class[0] != '.'' failed
> 
> (bakery-gui.py:1774): Gtk-CRITICAL **: 05:21:19.779: gtk_widget_add_css_class: assertion 'css_class[0] != '.'' failed
> 
> (bakery-gui.py:1774): Gtk-CRITICAL **: 05:21:19.779: gtk_widget_add_css_class: assertion 'css_class[0] != '.'' failed
>    ERROR: Error while processing disk /dev/sda: /dev/sda: unrecognised disk label
>    ERROR: Error while processing disk /dev/sr0: /dev/sr0: unrecognised disk label
> Traceback (most recent call last):
>    ERROR: Error while processing disk /dev/sda: /dev/sda: unrecognised disk label
>   File "/usr/share/bakery/bakery-gui.py", line 1456, in on_disk_selected
>     "Partition table: " + check_partition_table(self.disk)
>     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> TypeError: can only concatenate str (not "NoneType") to str
>    ERROR: Error while processing disk /dev/sda: /dev/sda: unrecognised disk label
> Traceback (most recent call last):
>   File "/usr/share/bakery/bakery.py", line 2463, in wrapped
>     result = func(*args, **kwargs)  # Call the original function
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/bakery/bakery.py", line 2451, in debounced
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/bakery/bakery-gui.py", line 263, in main_button_clicked
>     self.init_screens("offline")
>   File "/usr/share/bakery/bakery-gui.py", line 483, in init_screens
>     self.add_pages(self.stack1, self.pages)
>   File "/usr/share/bakery/bakery-gui.py", line 467, in add_pages
>     page_ = globals()[pages_dict[page][0]](window=self)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/bakery/bakery.py", line 2463, in wrapped
>     result = func(*args, **kwargs)  # Call the original function
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/bakery/bakery-gui.py", line 1190, in __init__
>     _("Partition table: ") + check_partition_table(self.disk)
>     ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> TypeError: can only concatenate str (not "NoneType") to str
> Function 'main_button_clicked' took 0.0000 seconds to execute.

**Comment by Rippanda12** [comment]
Could you please test again but before launching bakery run `sudo pacman -Sy bakery-gui bakery`?
